// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpWL4uPCjSuuBuUZeJ2NmixOznQr9X9KA',
    appId: '1:944751524873:web:1e306f8512e6a4c92b8cd8',
    messagingSenderId: '944751524873',
    projectId: 'bathroom-app-52749',
    authDomain: 'bathroom-app-52749.firebaseapp.com',
    storageBucket: 'bathroom-app-52749.appspot.com',
    measurementId: 'G-4GLKH6MV1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1s4N_nf3CdP4C8URVSggWqAgDm5KWMrE',
    appId: '1:944751524873:android:c364f6dbe10832192b8cd8',
    messagingSenderId: '944751524873',
    projectId: 'bathroom-app-52749',
    storageBucket: 'bathroom-app-52749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwuXfsKCYugIRq6H4YlBhXQ5tBn9_89nM',
    appId: '1:944751524873:ios:b8747706ef28b1122b8cd8',
    messagingSenderId: '944751524873',
    projectId: 'bathroom-app-52749',
    storageBucket: 'bathroom-app-52749.appspot.com',
    iosBundleId: 'com.example.bathroomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwuXfsKCYugIRq6H4YlBhXQ5tBn9_89nM',
    appId: '1:944751524873:ios:40acb113b532f1802b8cd8',
    messagingSenderId: '944751524873',
    projectId: 'bathroom-app-52749',
    storageBucket: 'bathroom-app-52749.appspot.com',
    iosBundleId: 'com.example.bathroomApp.RunnerTests',
  );
}
